### ISSUE TITLE
TypeError at /my/signup/: Object of type CSSessionObject is not JSON serializable

### ISSUE THREAD

**Issue by theova** [juntagrico/juntagrico#689]
When accessing https://intern.bergsolawi.ch/my/signup/, we get a 500 error.

We can reproduce this error with our [local Dockerfile](https://github.com/bergsolawi/bergsolawi/blob/master/Dockerfile).

We run juntagrico at 1.6.2.

Unfortunately, I cannot see where the problem exactly comes from, or what we need to change on our side. So we are happy for any further advice. Thanks a lot!

---

```
Environment:


Request Method: GET
Request URL: http://0.0.0.0:8000/my/signup/

Django Version: 4.2.13
Python Version: 3.9.19
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'juntagrico_webdav',
 'juntagrico',
 'fontawesomefree',
 'import_export',
 'impersonate',
 'crispy_forms',
 'adminsortable2',
 'bergsolawi',
 'polymorphic']
Installed Middleware:
['django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'impersonate.middleware.ImpersonateMiddleware',
 'django.contrib.sites.middleware.CurrentSiteMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/middleware.py", line 59, in process_response
    request.session.save()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 80, in save
    return self.create()
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 54, in create
    self.save(must_create=True)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 82, in save
    obj = self.create_model_instance(data)
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/db.py", line 69, in create_model_instance
    session_data=self.encode(data),
  File "/usr/local/lib/python3.9/site-packages/django/contrib/sessions/backends/base.py", line 94, in encode
    return signing.dumps(
  File "/usr/local/lib/python3.9/site-packages/django/core/signing.py", line 152, in dumps
    return TimestampSigner(key=key, salt=salt).sign_object(
  File "/usr/local/lib/python3.9/site-packages/django/core/signing.py", line 250, in sign_object
    data = serializer().dumps(obj)
  File "/usr/local/lib/python3.9/site-packages/django/core/signing.py", line 127, in dumps
    return json.dumps(obj, separators=(",", ":")).encode("latin-1")
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

Exception Type: TypeError at /my/signup/
Exception Value: Object of type CSSessionObject is not JSON serializable
```

**Comment by pascalfree** [comment]
You need to add this line back into your settings.py:

`SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'`

It got lost here: https://github.com/bergsolawi/bergsolawi/commit/d44725aa27e7526defdbf9cb36b09cfa06e4c335#diff-775b0f8bc6a72f25ce636489c9ce19a9e9ab9a2a29f7ebd431ffed284161dde4L141
