### ISSUE TITLE
Neuregistrierung mit Mitbezüger führt zu Server Error 500

### ISSUE THREAD

**Issue by patrickuhlmann** [juntagrico/juntagrico#742]
Eine Neuregistrierung kann nur ausgeführt werden, sofern kein Mitabonnen hinzugefügt wird. Wird ein Mitabonnent hinzugefügt, so erscheint einer "Server Error 500".

**Reproduktion**
1. Datei "Dockerfile" mit folgendem Inhalt erstellen:
```
FROM python:3.11
WORKDIR /opt

RUN wget --progress=dot:mega https://github.com/gartenbergCH/gartenberg/archive/refs/tags/v3.0.5.zip \
	&& unzip v3.0.5.zip gartenberg-3.0.5/* -d . \
	&& mv gartenberg-3.0.5/* . \
	&& rm v3.0.5.zip \
	&& pip install --no-cache-dir -r requirements.txt \
	&& chmod +x manage.py \
	&& ./manage.py migrate \
	&& export DJANGO_SUPERUSER_PASSWORD=secret \
	&& ./manage.py createsuperuser --noinput --username puh --email gartenberg@uhlme.ch \
	&& ./manage.py create_member_for_superusers \
	&& ./manage.py generate_testdata \
	&& ./manage.py collectstatic
ENV JUNTAGRICO_SECRET_KEY=secret
ENV JUNTAGRICO_EMAIL_HOST=mailcatcher
ENV JUNTAGRICO_EMAIL_USER=juntagrico
ENV JUNTAGRICO_EMAIL_PORT=1025
ENV JUNTAGRICO_EMAIL_TLS=False
EXPOSE 8000
CMD ["./manage.py", "runserver", "0.0.0.0:8000"]
```
2. Image builden ```docker build . --progress plain --no-cache --tag "gartenberg:3.0.5"```
3. Applikation starten ```docker run -it --rm -p 8000:8000 gartenberg:3.0.5```
4. Die Webseite unter localhost.8080 aufrufen
5. Auf "Registrieren und mitmachen!" klicken
6. Die Pflichtfelder ausfüllen und "Anmelden" klicken
7. "Ein Abo" auswählen und "Weiter" klicken
8. "Weiter klicken"
9. "Weiter klicken"
10. Einen Mitabonnent hinzufügen
11. Beim Klick auf "Fertig" kommt "Server Error (500)

Im Logfile erscheint
```
Internal Server Error: /my/create/subscription/shares/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
TypeError: 'Member' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/templatetags/i18n.py", line 156, in render
    {var: val.resolve(context) for var, val in self.extra_context.items()}
  File "/usr/local/lib/python3.11/site-packages/django/templatetags/i18n.py", line 156, in <dictcomp>
    {var: val.resolve(context) for var, val in self.extra_context.items()}
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/juntagrico/entity/member.py", line 80, in active_shares
    return self.share_set.active()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py", line 718, in get_queryset
    raise ValueError(
ValueError: 'Member' instance needs to have a primary key value before this relationship can be used.
```

**Comment by patrickuhlmann** [comment]
Habe versucht das Problem auf https://my.mehalsgmues.ch zu reproduzieren. Das klappte nicht. Als ich die GartenBerg Customizations entfernt hatte funktionierte es auch wieder. Versuche nun herauszufinden an welcher Customization es liegt.

**Comment by pascalfree** [comment]
Hoi @patrickuhlmann 

Das Problem, kommt von eurem Template:
Diese Zeile hier
https://github.com/gartenbergCH/gartenberg/blob/e5e8f989769dc61a64b55ac3dd9f10701f57ce3a/gartenberg/templates/createsubscription/select_shares.html#L92
muss angepasst werden auf:

    {% blocktrans trimmed with cac=co_member.active_shares_count %}
    
Also `active_shares_count` anstatt `active_shares.count`

**Comment by patrickuhlmann** [comment]
> Hoi @patrickuhlmann
> 
> Das Problem, kommt von eurem Template: Diese Zeile hier https://github.com/gartenbergCH/gartenberg/blob/e5e8f989769dc61a64b55ac3dd9f10701f57ce3a/gartenberg/templates/createsubscription/select_shares.html#L92 muss angepasst werden auf:
> 
> ```
> {% blocktrans trimmed with cac=co_member.active_shares_count %}
> ```
> 
> Also `active_shares_count` anstatt `active_shares.count`
> 
> Und am Besten auch in Zeile 77

Vielen Dank. Das Problem ist mit der vorgeschlagenen Anpassung gelöst
